#!/bin/bash

version="0.1.0"

bin_path=$(readlink -f ${BASH_SOURCE[0]})
root_path=$(echo "$bin_path" | sed 's|\(.*\)/.*|\1|')

create_command () {
	cmd_path="$root_path/cmd/$1"
	log_path="$root_path/cmd/stats/$1.log"
	link_path="$root_path/cmd/sym-links/$1-link"

	sudo touch $cmd_path
	chmod o+rx $cmd_path

	echo "#!/bin/bash" > $cmd_path
	echo "echo \"$version \$(date +%Y-%m-%d-%H-%M-%S) \$(whoami) \" >> $log_path" >> $cmd_path
	echo "bash $link_path \$@" >> $cmd_path

	sudo touch $log_path
	chmod o+rw $log_path
}

delete_command () {
	cmd_path="$root_path/cmd/$1"
	log_path="$root_path/cmd/stats/$1.log"
	link_path="$root_path/cmd/sym-links/$1-link"

	rm $cmd_path
	rm $log_path
	rm $link_path
}

while test -n "$1"; do
	case $1 in
		-h|--help)
			echo "Usage: sts.sh [-h|--help] new <name> <bash-file>"
			;;
		
		-v|--version)
			echo "sts version $version"
			;;

		new)
			command_name=$2
			bash_file=$3
			ln -srf "$bash_file" "$root_path/cmd/sym-links/$command_name-link"
			create_command $command_name
			shift; shift
			;;

		remove)
			delete_command $2
			shift
			;;

		refresh)
			command_name=$2
			bash_file=$3
			delete_command $command_name
			ln -srf "$bash_file" "$root_path/cmd/sym-links/$command_name-link"
			create_command $command_name
			shift; shift
			;;

		install)
			mkdir -p /usr/local/lib/sts/cmd/sym-links
			echo "[1] created directory /usr/local/lib/sts/cmd/sym-links"

			mkdir -p /usr/local/lib/sts/cmd/stats
			echo "[2] created directory /usr/local/lib/sts/cmd/stats"

			cp $bin_path /usr/local/lib/sts/sts
			echo "[3] Copied sts to /usr/local/lib/sts"

			ln -s /usr/local/lib/sts/sts /usr/local/bin/sts
			echo "[4] created symlink from /usr/local/lib/sts/sts to /usr/local/bin/sts"

			echo "[5] Add: export PATH=\$PATH:\"...:/usr/local/lib/sts/cmd\" to your .bashrc or .zshrc file"
			;;

		uninstall)
			rm -rf /usr/local/lib/sts
			echo "[1] Removed sts from /usr/local/lib/sts"

			rm /usr/local/bin/sts
			echo "[2] removed symlink from /usr/local/bin/sts"

			echo "[3] remove: export PATH=\$PATH:\"...:/usr/local/lib/sts/cmd\" from your .bashrc or .zshrc file"
			;;

		*)
			echo $(readlink -f ${BASH_SOURCE[0]})
			echo "sts: Unknown command: $1"
			;;
	esac
	shift
done
