#!/bin/bash

bin_path=$(readlink -f ${BASH_SOURCE[0]})
root_path=$(echo "$bin_path" | sed 's|\(.*\)/.*|\1|')

create_command () {
	cmd_path="$root_path/cmd/$1"

	sudo touch $cmd_path
	chmod o+rx $cmd_path

	echo "#!/bin/bash" > $cmd_path
	echo "bash $root_path/cmd/sys-links/$1-link" >> $cmd_path
}

while test -n "$1"; do
	case $1 in
		-h|--help)
			echo "Usage: sts.sh [-h|--help] <name> <bash-file>"
			;;
		new)
			command_name=$2
			bash_file=$3
			ln -srf "$bash_file" "$root_path/cmd/sys-links/$command_name-link"
			create_command "$command_name"
			shift; shift
			;;
			*)
				echo $(readlink -f ${BASH_SOURCE[0]})
				echo "sts: Unknown command: $1"
			;;
	esac
	shift
done
