#!/bin/bash
echo "0.1.0 $(date +%Y-%m-%d-%H-%M-%S) $(whoami) " >> /home/lorenz/Documents/github/bbw/m122-ruet-bash_abschluss_project-lorenzhohermuth/cmd/stats/verify.log
bash /home/lorenz/Documents/github/bbw/m122-ruet-bash_abschluss_project-lorenzhohermuth/cmd/sym-links/verify-link $@
